---
# tasks file for /home/centos/.ansible/roles/database
- name: Re-create a database container
  community.docker.docker_container:
    name: db
    image: rastokmeepf/tp-devops-database:latest
    state: started
    env:
        POSTGRES_DB: db
        POSTGRES_USER: usr
        POSTGRES_PASSWORD: pwd
    networks:
      - name: app_network
