---
# tasks file for roles/proxy
- name: Create proxy
  community.docker.docker_container:
    name: httpd
    image: rastokmeepf/tp-devops-httpd:latest
    state: started
    networks:
      - name: app_network
    ports:
      - "80:80"
