name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./httpd
        push: true
        tags: rastokmeepf/tp1-httpd:latest

    - name: Build and push simple-api image
      uses: docker/build-push-action@v2
      with:
        context: ./other-services
        push: true
        tags: rastokmeepf/tp1-simple-api:latest

    - name: Build and push database image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rastokmeepf/tp1-db:latest

    - name: Run tests
      run: |
        # Add commands to run your tests here
        echo "Running tests..."
