name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build and test with Maven
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=rastokme_tp1 -Dsonar.organization=rastokme -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml


  build-and-push-docker-image:
    needs: build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push simple-api image
      uses: docker/build-push-action@v3
      with:
        context: ./simple-api
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest

    - name: Build and push httpd image
      uses: docker/build-push-action@v3
      with:
        context: ./httpd
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
